  export const videos = [
    'https://videos.pexels.com/video-files/852286/852286-hd_1920_1080_30fps.mp4',
    'https://videos.pexels.com/video-files/2871918/2871918-hd_1920_1080_30fps.mp4',
    'https://videos.pexels.com/video-files/3015491/3015491-hd_1920_1080_24fps.mp4',
    'https://videos.pexels.com/video-files/1448735/1448735-uhd_2732_1440_24fps.mp4',
    'https://videos.pexels.com/video-files/3194277/3194277-hd_1920_1080_30fps.mp4'

  ];

  export const TrendingMoviesList = [
    {
      id: 0,
      title: "Movie 1",
      year: "2023",
      storyline:
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Obcaecati quo id excepturi similique veritatis quisquam at consequatur atque illo dolore optio, nesciunt nulla quam quidem. Dolor delectus illo est itaque.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Obcaecati quo id excepturi similique veritatis quisquam at consequatur atque illo dolore optio, nesciunt nulla quam quidem. Dolor delectus illo est itaque.",
      releaseDate: "2023-01-01",
      genres: ["Action", "Thriller"],
      actors: ["Actor A", "Actor B"],
      imdbRating: 8.5,
      averageRating: 4.5,
      poster: "https://www.ottking.info/wp-content/uploads/2024/09/disco-p-1.jpg",
    },
    {
      id: 1,
      title: "Movie 2",
      year: "2021",
      storyline:
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Obcaecati quo id excepturi similique veritatis quisquam at consequatur atque illo dolore optio, nesciunt nulla quam quidem. Dolor delectus illo est itaque.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Obcaecati quo id excepturi similique veritatis quisquam at consequatur atque illo dolore optio, nesciunt nulla quam quidem. Dolor delectus illo est itaque.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Obcaecati quo id excepturi similique veritatis quisquam at consequatur atque illo dolore optio, nesciunt nulla quam quidem. Dolor delectus illo est itaque.",
      releaseDate: "2021-05-15",
      genres: ["Comedy", "Drama"],
      actors: ["Actor X", "Actor Y"],
      imdbRating: 7.3,
      averageRating: 4.0,
      poster:
        "https://m.media-amazon.com/images/M/MV5BNGE0NzE5Y2ItYjQ3Zi00YzNiLWFhNmMtODhkNjFhNzQ5ZGFlXkEyXkFqcGc@._V1_.jpg",
    },
    {
      id: 2,
      title: "Movie 1",
      year: "2023",
      storyline:
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Obcaecati quo id excepturi similique veritatis quisquam at consequatur atque illo dolore optio, nesciunt nulla quam quidem. Dolor delectus illo est itaque.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Obcaecati quo id excepturi similique veritatis quisquam at consequatur atque illo dolore optio, nesciunt nulla quam quidem. Dolor delectus illo est itaque.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Obcaecati quo id excepturi similique veritatis quisquam at consequatur atque illo dolore optio, nesciunt nulla quam quidem. Dolor delectus illo est itaque.",
      releaseDate: "2023-01-01",
      genres: ["Action", "Thriller"],
      actors: ["Actor A", "Actor B"],
      imdbRating: 8.5,
      averageRating: 4.5,
      poster: "https://www.ottking.info/wp-content/uploads/2024/09/agent.jpg",
    },
    {
      id: 3,
      title: "Movie 2",
      year: "2021",
      storyline: "This is the storyline for Movie 2.",
      releaseDate: "2021-05-15",
      genres: ["Comedy", "Drama"],
      actors: ["Actor X", "Actor Y"],
      imdbRating: 7.3,
      averageRating: 4.0,
      poster:
        "https://www.ottking.info/wp-content/uploads/2024/09/HOI.jpg",
    },
    {
      id: 4,
      title: "Movie 1",
      year: "2023",
      storyline: "This is the storyline for Movie 1.",
      releaseDate: "2023-01-01",
      genres: ["Action", "Thriller"],
      actors: ["Actor A", "Actor B"],
      imdbRating: 8.5,
      averageRating: 4.5,
      poster: "https://www.ottking.info/wp-content/uploads/2024/09/Untitled-design-20.jpg",
    },
    {
      id: 5,
      title: "Movie 2",
      year: "2021",
      storyline: "This is the storyline for Movie 2.",
      releaseDate: "2021-05-15",
      genres: ["Comedy", "Drama"],
      actors: ["Actor X", "Actor Y"],
      imdbRating: 7.3,
      averageRating: 4.0,
      poster:
        "https://www.ottking.info/wp-content/uploads/2024/09/Untitled-design-BERLIN.jpg",
    },
    {
      id: 6,
      title: "Movie 1",
      year: "2023",
      storyline: "This is the storyline for Movie 1.",
      releaseDate: "2023-01-01",
      genres: ["Action", "Thriller"],
      actors: ["Actor A", "Actor B"],
      imdbRating: 8.5,
      averageRating: 4.5,
      poster: "https://m.media-amazon.com/images/I/915xJIYLb+L.jpg",
    },
    {
      id: 7,
      title: "Movie 2",
      year: "2021",
      storyline: "This is the storyline for Movie 2.",
      releaseDate: "2021-05-15",
      genres: ["Comedy", "Drama"],
      actors: ["Actor X", "Actor Y"],
      imdbRating: 7.3,
      averageRating: 4.0,
      poster:
        "https://m.media-amazon.com/images/M/MV5BNGE0NzE5Y2ItYjQ3Zi00YzNiLWFhNmMtODhkNjFhNzQ5ZGFlXkEyXkFqcGc@._V1_.jpg",
    },
  ];

  export const NewlyReleasedMoviesList = [
    {
      id: 0,
      title: "Movie 1",
      year: "2023",
      storyline: "This is the storyline for Movie 1.",
      releaseDate: "2023-01-01",
      genres: ["Action", "Thriller"],
      actors: ["Actor A", "Actor B"],
      imdbRating: 8.5,
      averageRating: 4.5,
      poster: "https://www.ottking.info/wp-content/uploads/2024/09/fli.jpg",
    },
    {
      id: 1,
      category: "Newly-released-movies",
      title: "Movie 2",
      year: "2021",
      storyline: "This is the storyline for Movie 2.",
      releaseDate: "2021-05-15",
      genres: ["Comedy", "Drama"],
      actors: ["Actor X", "Actor Y"],
      imdbRating: 7.3,
      averageRating: 4.0,
      poster:
        "https://www.ottking.info/wp-content/uploads/2024/09/Untitled-design-tej.jpg",
    },
    {
      id: 2,
      category: "Newly-released-movies",
      title: "Movie 3",
      year: "2023",
      storyline: "This is the storyline for Movie 1.",
      releaseDate: "2023-01-01",
      genres: ["Action", "Thriller"],
      actors: ["Actor A", "Actor B"],
      imdbRating: 8.5,
      averageRating: 4.5,
      poster: "https://www.ottking.info/wp-content/uploads/2024/09/lgp.jpg",
    },
    {
      id: 3,
      category: "Newly-released-movies",
      title: "Movie 4",
      year: "2021",
      storyline: "This is the storyline for Movie 2.",
      releaseDate: "2021-05-15",
      genres: ["Comedy", "Drama"],
      actors: ["Actor X", "Actor Y"],
      imdbRating: 7.3,
      averageRating: 4.0,
      poster:
        "https://www.ottking.info/wp-content/uploads/2024/09/kk.jpg",
    },
    {
      id: 4,
      category: "Newly-released-movies",
      title: "Movie 5",
      year: "2023",
      storyline: "This is the storyline for Movie 1.",
      releaseDate: "2023-01-01",
      genres: ["Action", "Thriller"],
      actors: ["Actor A", "Actor B"],
      imdbRating: 8.5,
      averageRating: 4.5,
      poster: "https://www.ottking.info/wp-content/uploads/2024/09/win.jpg",
    },
    {
      id: 5,
      category: "Newly-released-movies",
      title: "Movie 6",
      year: "2021",
      storyline: "This is the storyline for Movie 2.",
      releaseDate: "2021-05-15",
      genres: ["Comedy", "Drama"],
      actors: ["Actor X", "Actor Y"],
      imdbRating: 7.3,
      averageRating: 4.0,
      poster:
        "https://www.ottking.info/wp-content/uploads/2024/09/par.jpg",
    },
    {
      id: 6,
      category: "Newly-released-movies",
      title: "Movie 7",
      year: "2023",
      storyline: "This is the storyline for Movie 1.",
      releaseDate: "2023-01-01",
      genres: ["Action", "Thriller"],
      actors: ["Actor A", "Actor B"],
      imdbRating: 8.5,
      averageRating: 4.5,
      poster: "https://m.media-amazon.com/images/I/915xJIYLb+L.jpg",
    },
    {
      id: 7,
      category: "Newly-released-movies",
      title: "Movie 2",
      year: "2021",
      storyline: "This is the storyline for Movie 2.",
      releaseDate: "2021-05-15",
      genres: ["Comedy", "Drama"],
      actors: ["Actor X", "Actor Y"],
      imdbRating: 7.3,
      averageRating: 4.0,
      poster:
        "https://m.media-amazon.com/images/M/MV5BNGE0NzE5Y2ItYjQ3Zi00YzNiLWFhNmMtODhkNjFhNzQ5ZGFlXkEyXkFqcGc@._V1_.jpg",
    },
  ];