  export const videos = [
    'https://videos.pexels.com/video-files/852286/852286-hd_1920_1080_30fps.mp4',
    'https://videos.pexels.com/video-files/2871918/2871918-hd_1920_1080_30fps.mp4',
    'https://videos.pexels.com/video-files/3015491/3015491-hd_1920_1080_24fps.mp4',
    'https://videos.pexels.com/video-files/1448735/1448735-uhd_2732_1440_24fps.mp4',
    'https://videos.pexels.com/video-files/3194277/3194277-hd_1920_1080_30fps.mp4'

  ];

  export const logos = [
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
    'https://upload.wikimedia.org/wikipedia/commons/5/5a/Zee5-official-logo.jpeg',
    'https://play-lh.googleusercontent.com/-qJGSkZMRoaFIk4dwqwWQ_mRIFs5XbeX2GIXv8S4vq8YzaHJ5boOEwjayyZY8G0u2jE',
    'https://play-lh.googleusercontent.com/27MJyZrte7jaPCkmXETN6-6Bry93Tmb4Jmz3rREJrDrjQ0HNcXrlD90KrNkf6L_bpDw',
    'https://play-lh.googleusercontent.com/bIYlrMjal6an_GSBsn-k6NevSC5yv7q_0ej8ZVM_1Br_UEeG0-chDO2xS5JI4Xw3sQ',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
    'https://upload.wikimedia.org/wikipedia/commons/5/5a/Zee5-official-logo.jpeg',
    'https://play-lh.googleusercontent.com/-qJGSkZMRoaFIk4dwqwWQ_mRIFs5XbeX2GIXv8S4vq8YzaHJ5boOEwjayyZY8G0u2jE',
    'https://play-lh.googleusercontent.com/27MJyZrte7jaPCkmXETN6-6Bry93Tmb4Jmz3rREJrDrjQ0HNcXrlD90KrNkf6L_bpDw',
    'https://play-lh.googleusercontent.com/bIYlrMjal6an_GSBsn-k6NevSC5yv7q_0ej8ZVM_1Br_UEeG0-chDO2xS5JI4Xw3sQ',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
    'https://upload.wikimedia.org/wikipedia/commons/5/5a/Zee5-official-logo.jpeg',
    'https://play-lh.googleusercontent.com/-qJGSkZMRoaFIk4dwqwWQ_mRIFs5XbeX2GIXv8S4vq8YzaHJ5boOEwjayyZY8G0u2jE',
    'https://play-lh.googleusercontent.com/27MJyZrte7jaPCkmXETN6-6Bry93Tmb4Jmz3rREJrDrjQ0HNcXrlD90KrNkf6L_bpDw',
    'https://play-lh.googleusercontent.com/bIYlrMjal6an_GSBsn-k6NevSC5yv7q_0ej8ZVM_1Br_UEeG0-chDO2xS5JI4Xw3sQ',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s'
  ]; 

  export const TrendingMoviesList = [
    {
      id: 0,
      title: "Movie 1",
      year: "2023",
      storyline:
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Obcaecati quo id excepturi similique veritatis quisquam at consequatur atque illo dolore optio, nesciunt nulla quam quidem. Dolor delectus illo est itaque.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Obcaecati quo id excepturi similique veritatis quisquam at consequatur atque illo dolore optio, nesciunt nulla quam quidem. Dolor delectus illo est itaque.",
      releaseDate: "2023-01-01",
      genres: ["Action", "Thriller"],
      actors: ["Actor A", "Actor B"],
      imdbRating: 8.5,
      averageRating: 4.5,
      poster: "https://www.ottking.info/wp-content/uploads/2024/09/disco-p-1.jpg",
    },
    {
      id: 1,
      title: "Movie 2",
      year: "2021",
      storyline:
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Obcaecati quo id excepturi similique veritatis quisquam at consequatur atque illo dolore optio, nesciunt nulla quam quidem. Dolor delectus illo est itaque.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Obcaecati quo id excepturi similique veritatis quisquam at consequatur atque illo dolore optio, nesciunt nulla quam quidem. Dolor delectus illo est itaque.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Obcaecati quo id excepturi similique veritatis quisquam at consequatur atque illo dolore optio, nesciunt nulla quam quidem. Dolor delectus illo est itaque.",
      releaseDate: "2021-05-15",
      genres: ["Comedy", "Drama"],
      actors: ["Actor X", "Actor Y"],
      imdbRating: 7.3,
      averageRating: 4.0,
      poster:
        "https://m.media-amazon.com/images/M/MV5BNGE0NzE5Y2ItYjQ3Zi00YzNiLWFhNmMtODhkNjFhNzQ5ZGFlXkEyXkFqcGc@._V1_.jpg",
    },
    {
      id: 2,
      title: "Movie 1",
      year: "2023",
      storyline:
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Obcaecati quo id excepturi similique veritatis quisquam at consequatur atque illo dolore optio, nesciunt nulla quam quidem. Dolor delectus illo est itaque.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Obcaecati quo id excepturi similique veritatis quisquam at consequatur atque illo dolore optio, nesciunt nulla quam quidem. Dolor delectus illo est itaque.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Obcaecati quo id excepturi similique veritatis quisquam at consequatur atque illo dolore optio, nesciunt nulla quam quidem. Dolor delectus illo est itaque.",
      releaseDate: "2023-01-01",
      genres: ["Action", "Thriller"],
      actors: ["Actor A", "Actor B"],
      imdbRating: 8.5,
      averageRating: 4.5,
      poster: "https://www.ottking.info/wp-content/uploads/2024/09/agent.jpg",
    },
    {
      id: 3,
      title: "Movie 2",
      year: "2021",
      storyline: "This is the storyline for Movie 2.",
      releaseDate: "2021-05-15",
      genres: ["Comedy", "Drama"],
      actors: ["Actor X", "Actor Y"],
      imdbRating: 7.3,
      averageRating: 4.0,
      poster:
        "https://www.ottking.info/wp-content/uploads/2024/09/HOI.jpg",
    },
    {
      id: 4,
      title: "Movie 1",
      year: "2023",
      storyline: "This is the storyline for Movie 1.",
      releaseDate: "2023-01-01",
      genres: ["Action", "Thriller"],
      actors: ["Actor A", "Actor B"],
      imdbRating: 8.5,
      averageRating: 4.5,
      poster: "https://www.ottking.info/wp-content/uploads/2024/09/Untitled-design-20.jpg",
    },
    {
      id: 5,
      title: "Movie 2",
      year: "2021",
      storyline: "This is the storyline for Movie 2.",
      releaseDate: "2021-05-15",
      genres: ["Comedy", "Drama"],
      actors: ["Actor X", "Actor Y"],
      imdbRating: 7.3,
      averageRating: 4.0,
      poster:
        "https://www.ottking.info/wp-content/uploads/2024/09/Untitled-design-BERLIN.jpg",
    },
    {
      id: 6,
      title: "Movie 1",
      year: "2023",
      storyline: "This is the storyline for Movie 1.",
      releaseDate: "2023-01-01",
      genres: ["Action", "Thriller"],
      actors: ["Actor A", "Actor B"],
      imdbRating: 8.5,
      averageRating: 4.5,
      poster: "https://m.media-amazon.com/images/I/915xJIYLb+L.jpg",
    },
    {
      id: 7,
      title: "Movie 2",
      year: "2021",
      storyline: "This is the storyline for Movie 2.",
      releaseDate: "2021-05-15",
      genres: ["Comedy", "Drama"],
      actors: ["Actor X", "Actor Y"],
      imdbRating: 7.3,
      averageRating: 4.0,
      poster:
        "https://m.media-amazon.com/images/M/MV5BNGE0NzE5Y2ItYjQ3Zi00YzNiLWFhNmMtODhkNjFhNzQ5ZGFlXkEyXkFqcGc@._V1_.jpg",
    },
  ];

  export const NewlyReleasedMoviesList = [
    {
      id: 0,
      title: "Movie 1",
      year: "2023",
      storyline: "This is the storyline for Movie 1.",
      releaseDate: "2023-01-01",
      genres: ["Action", "Thriller"],
      actors: ["Actor A", "Actor B"],
      imdbRating: 8.5,
      averageRating: 4.5,
      poster: "https://www.ottking.info/wp-content/uploads/2024/09/fli.jpg",
    },
    {
      id: 1,
      category: "Newly-released-movies",
      title: "Movie 2",
      year: "2021",
      storyline: "This is the storyline for Movie 2.",
      releaseDate: "2021-05-15",
      genres: ["Comedy", "Drama"],
      actors: ["Actor X", "Actor Y"],
      imdbRating: 7.3,
      averageRating: 4.0,
      poster:
        "https://www.ottking.info/wp-content/uploads/2024/09/Untitled-design-tej.jpg",
    },
    {
      id: 2,
      category: "Newly-released-movies",
      title: "Movie 3",
      year: "2023",
      storyline: "This is the storyline for Movie 1.",
      releaseDate: "2023-01-01",
      genres: ["Action", "Thriller"],
      actors: ["Actor A", "Actor B"],
      imdbRating: 8.5,
      averageRating: 4.5,
      poster: "https://www.ottking.info/wp-content/uploads/2024/09/lgp.jpg",
    },
    {
      id: 3,
      category: "Newly-released-movies",
      title: "Movie 4",
      year: "2021",
      storyline: "This is the storyline for Movie 2.",
      releaseDate: "2021-05-15",
      genres: ["Comedy", "Drama"],
      actors: ["Actor X", "Actor Y"],
      imdbRating: 7.3,
      averageRating: 4.0,
      poster:
        "https://www.ottking.info/wp-content/uploads/2024/09/kk.jpg",
    },
    {
      id: 4,
      category: "Newly-released-movies",
      title: "Movie 5",
      year: "2023",
      storyline: "This is the storyline for Movie 1.",
      releaseDate: "2023-01-01",
      genres: ["Action", "Thriller"],
      actors: ["Actor A", "Actor B"],
      imdbRating: 8.5,
      averageRating: 4.5,
      poster: "https://www.ottking.info/wp-content/uploads/2024/09/win.jpg",
    },
    {
      id: 5,
      category: "Newly-released-movies",
      title: "Movie 6",
      year: "2021",
      storyline: "This is the storyline for Movie 2.",
      releaseDate: "2021-05-15",
      genres: ["Comedy", "Drama"],
      actors: ["Actor X", "Actor Y"],
      imdbRating: 7.3,
      averageRating: 4.0,
      poster:
        "https://www.ottking.info/wp-content/uploads/2024/09/par.jpg",
    },
    {
      id: 6,
      category: "Newly-released-movies",
      title: "Movie 7",
      year: "2023",
      storyline: "This is the storyline for Movie 1.",
      releaseDate: "2023-01-01",
      genres: ["Action", "Thriller"],
      actors: ["Actor A", "Actor B"],
      imdbRating: 8.5,
      averageRating: 4.5,
      poster: "https://m.media-amazon.com/images/I/915xJIYLb+L.jpg",
    },
    {
      id: 7,
      category: "Newly-released-movies",
      title: "Movie 2",
      year: "2021",
      storyline: "This is the storyline for Movie 2.",
      releaseDate: "2021-05-15",
      genres: ["Comedy", "Drama"],
      actors: ["Actor X", "Actor Y"],
      imdbRating: 7.3,
      averageRating: 4.0,
      poster:
        "https://m.media-amazon.com/images/M/MV5BNGE0NzE5Y2ItYjQ3Zi00YzNiLWFhNmMtODhkNjFhNzQ5ZGFlXkEyXkFqcGc@._V1_.jpg",
    },
  ];

  export const BannerOneData = {
    title: "Almost Adults", 
    description: "This comedy feature follows two best friends in their final year of college while they transition into adulthood. One embraces her sexuality and….", 
    image: "https://www.pixelstalk.net/wp-content/uploads/images6/5K-Wallpaper-HD-Free-download.jpg",
    video: "https://www.youtube.com/watch?v=5PSNL1qE6VY"
  }

  export const BannerTwoData = {
    // image: 'https://images4.alphacoders.com/673/thumb-1920-673780.jpg',
    image: 'https://windybot.com/img/obEdfxX5On2KtqfunkBR.jpg',
    preTitle: 'A NETFLIX SERIES',
    title: 'A Messenger From Space',
    date: 'December 4',
    logo: 'https://thewhitonline.com/wp-content/uploads/2020/09/netflix-logo.png'
  }

  export const BannerThreeData = {
    logo: 'https://wallpaper.forfun.com/fetch/f8/f8189d0a36f59ab9f519b38158383575.jpeg',
    subheading: 'New Series',
    heading: 'House of The Dragon',
    date: 'December 1'
  }

  export const TrendingTVShowsList = [
    {
      id: 0,
      title: "Shark Tank",
      year: "2024",
      storyline:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati quo id excepturi similique veritatis quisquam at consequatur atque illo dolore optio.",
      releaseDate: "2024-01-01",
      genres: ["Reality", "Business"],
      actors: ["Entrepreneur A", "Investor B"],
      imdbRating: 7.8,
      averageRating: 4.2,
      poster: "https://www.ottking.info/wp-content/uploads/2024/03/shark-tank-1.jpg",
    },
    {
      id: 1,
      title: "Sa Re Ga Ma Pa",
      year: "2023",
      storyline:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati quo id excepturi similique veritatis quisquam at consequatur atque illo dolore optio.",
      releaseDate: "2023-11-15",
      genres: ["Music", "Reality"],
      actors: ["Singer X", "Judge Y"],
      imdbRating: 8.0,
      averageRating: 4.5,
      poster: "https://www.ottking.info/wp-content/uploads/2023/11/Watch-Now-sa-ra-ga.jpg",
    },
    {
      id: 2,
      title: "Show 77",
      year: "2023",
      storyline:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati quo id excepturi similique veritatis quisquam at consequatur atque illo dolore optio.",
      releaseDate: "2023-11-10",
      genres: ["Drama", "Thriller"],
      actors: ["Actor A", "Actor B"],
      imdbRating: 7.5,
      averageRating: 4.1,
      poster: "https://www.ottking.info/wp-content/uploads/2023/11/Watch-Now-77.jpg",
    },
    {
      id: 3,
      title: "Epic On",
      year: "2023",
      storyline:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati quo id excepturi similique veritatis quisquam at consequatur atque illo dolore optio.",
      releaseDate: "2023-11-05",
      genres: ["Documentary", "History"],
      actors: ["Narrator X", "Actor Y"],
      imdbRating: 8.3,
      averageRating: 4.6,
      poster: "https://www.ottking.info/wp-content/uploads/2023/11/Watch-Now-epic-on.jpg",
    },
    {
      id: 4,
      title: "Daakan",
      year: "2023",
      storyline:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati quo id excepturi similique veritatis quisquam at consequatur atque illo dolore optio.",
      releaseDate: "2023-11-01",
      genres: ["Horror", "Drama"],
      actors: ["Actor X", "Actor Z"],
      imdbRating: 7.2,
      averageRating: 3.9,
      poster: "https://www.ottking.info/wp-content/uploads/2023/11/daakan.jpg",
    },
    {
      id: 5,
      title: "Random Show 1",
      year: "2024",
      storyline:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati quo id excepturi similique veritatis quisquam at consequatur atque illo dolore optio.",
      releaseDate: "2024-02-15",
      genres: ["Drama", "Action"],
      actors: ["Actor Y", "Actor Z"],
      imdbRating: 7.9,
      averageRating: 4.4,
      poster: "https://m.media-amazon.com/images/I/915xJIYLb+L.jpg",
    },
    {
      id: 6,
      title: "Random Show 2",
      year: "2024",
      storyline:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati quo id excepturi similique veritatis quisquam at consequatur atque illo dolore optio.",
      releaseDate: "2024-03-10",
      genres: ["Comedy", "Reality"],
      actors: ["Actor A", "Actor B"],
      imdbRating: 7.6,
      averageRating: 4.3,
      poster: "https://m.media-amazon.com/images/I/915xJIYLb+L.jpg",
    },
    {
      id: 7,
      title: "Random Show 3",
      year: "2024",
      storyline:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati quo id excepturi similique veritatis quisquam at consequatur atque illo dolore optio.",
      releaseDate: "2024-04-05",
      genres: ["Drama", "Mystery"],
      actors: ["Actor X", "Actor Y"],
      imdbRating: 7.4,
      averageRating: 4.0,
      poster: "https://m.media-amazon.com/images/I/915xJIYLb+L.jpg",
    },
  ];  

  export const OTTKingMoviesList = [
    {
      id: 0,
      title: "Movie Title 1",
      poster: "https://m.media-amazon.com/images/I/915xJIYLb+L.jpg",
      releaseDate: "2023-11-01",
      genres: ["Action", "Adventure"],
      imdbRating: 7.5,
    },
    {
      id: 1,
      title: "Movie Title 2",
      poster: "https://m.media-amazon.com/images/M/MV5BNGE0NzE5Y2ItYjQ3Zi00YzNiLWFhNmMtODhkNjFhNzQ5ZGFlXkEyXkFqcGc@._V1_.jpg",
      releaseDate: "2023-12-10",
      genres: ["Comedy", "Drama"],
      imdbRating: 8.2,
    },
    {
      id: 2,
      title: "Movie Title 3",
      poster: "https://m.media-amazon.com/images/I/915xJIYLb+L.jpg",
      releaseDate: "2023-11-15",
      genres: ["Thriller", "Mystery"],
      imdbRating: 6.9,
    },
    {
      id: 3,
      title: "Movie Title 4",
      poster: "https://m.media-amazon.com/images/I/915xJIYLb+L.jpg",
      releaseDate: "2023-12-01",
      genres: ["Action", "Sci-Fi"],
      imdbRating: 7.8,
    },
    {
      id: 4,
      title: "Movie Title 5",
      poster: "https://m.media-amazon.com/images/I/915xJIYLb+L.jpg",
      releaseDate: "2023-12-05",
      genres: ["Drama", "Romance"],
      imdbRating: 7.4,
    },
    {
      id: 5,
      title: "Movie Title 6",
      poster: "https://m.media-amazon.com/images/I/915xJIYLb+L.jpg",
      releaseDate: "2023-12-15",
      genres: ["Animation", "Family"],
      imdbRating: 8.0,
    },
    {
      id: 6,
      title: "Movie Title 7",
      poster: "https://m.media-amazon.com/images/I/915xJIYLb+L.jpg",
      releaseDate: "2023-11-20",
      genres: ["Horror", "Thriller"],
      imdbRating: 6.7,
    },
    {
      id: 7,
      title: "Movie Title 8",
      poster: "https://m.media-amazon.com/images/I/915xJIYLb+L.jpg",
      releaseDate: "2023-12-25",
      genres: ["Adventure", "Fantasy"],
      imdbRating: 7.9,
    },
  ];

  export const KidsShowList = [
    {
      id: 0,
      title: "Adventures in Toyland",
      year: "2023",
      storyline: "Join Timmy and his friends as they explore the magical world of Toyland, where every toy comes to life!",
      releaseDate: "2023-11-01",
      genres: ["Animation", "Adventure", "Family"],
      actors: ["Actor P", "Actor Q"],
      imdbRating: 7.8,
      averageRating: 4.2,
      poster: "https://www.ottking.info/wp-content/uploads/2023/11/Untitled-design-5-5.jpg",
    },
    {
      id: 1,
      title: "Magic Balloon Ride",
      year: "2023",
      storyline: "Hop on a magical hot air balloon with Lily and her puppy as they soar across the sky, discovering new lands and making new friends.",
      releaseDate: "2023-12-10",
      genres: ["Animation", "Fantasy", "Family"],
      actors: ["Actor R", "Actor S"],
      imdbRating: 8.2,
      averageRating: 4.5,
      poster: "https://www.ottking.info/wp-content/uploads/2023/12/Untitled-design-guru.jpg",
    },
    {
      id: 2,
      title: "Super Dino Squad",
      year: "2023",
      storyline: "Meet the Super Dino Squad, a team of friendly dinosaurs who embark on exciting adventures to save their prehistoric world!",
      releaseDate: "2023-11-15",
      genres: ["Animation", "Action", "Family"],
      actors: ["Actor T", "Actor U"],
      imdbRating: 6.9,
      averageRating: 3.8,
      poster: "https://www.ottking.info/wp-content/uploads/2023/11/WATCH-NOW-GOPAL.jpg",
    },
    {
      id: 3,
      title: "Pirates of the Rainbow Island",
      year: "2023",
      storyline: "Sail the seas with Captain Rainbow and her crew of young pirates as they search for hidden treasures on a colorful island full of surprises!",
      releaseDate: "2023-12-01",
      genres: ["Animation", "Adventure", "Family"],
      actors: ["Actor V", "Actor W"],
      imdbRating: 7.5,
      averageRating: 4.0,
      poster: "https://www.ottking.info/wp-content/uploads/2023/12/Untitled-design-lk.jpg",
    },
    {
      id: 4,
      title: "Funky Farmyard Friends",
      year: "2023",
      storyline: "Join the fun-loving animals of Funky Farmyard as they learn life lessons and share laughter on their daily farm adventures.",
      releaseDate: "2023-12-20",
      genres: ["Animation", "Comedy", "Family"],
      actors: ["Actor X", "Actor Y"],
      imdbRating: 7.3,
      averageRating: 4.1,
      poster: "https://www.ottking.info/wp-content/uploads/2023/12/Untitled-design-bj.jpg",
    },
    {
      id: 5,
      title: "Giant Cloud Adventures",
      year: "2023",
      storyline: "Fly high with Max and his best friend Sky as they ride on magical clouds and explore floating islands filled with wonder and mystery!",
      releaseDate: "2023-11-25",
      genres: ["Animation", "Fantasy", "Family"],
      actors: ["Actor Z", "Actor A"],
      imdbRating: 7.6,
      averageRating: 4.3,
      poster: "https://www.ottking.info/wp-content/uploads/2023/11/WATCH-NOW-GOPAL.jpg",
    },
    {
      id: 6,
      title: "The Colorful Jungle",
      year: "2023",
      storyline: "Follow Ellie the Elephant and her friends as they journey through a vibrant jungle to solve puzzles and help their animal buddies.",
      releaseDate: "2023-12-15",
      genres: ["Animation", "Adventure", "Family"],
      actors: ["Actor B", "Actor C"],
      imdbRating: 7.4,
      averageRating: 4.2,
      poster: "https://www.ottking.info/wp-content/uploads/2023/12/Untitled-design-lk.jpg",
    },
    {
      id: 7,
      title: "Underwater Wonders",
      year: "2023",
      storyline: "Dive into the magical underwater world of Coral Kingdom with Sammy the Seahorse and his friends as they protect the ocean and its secrets.",
      releaseDate: "2023-12-05",
      genres: ["Animation", "Fantasy", "Family"],
      actors: ["Actor D", "Actor E"],
      imdbRating: 8.0,
      averageRating: 4.4,
      poster: "https://www.ottking.info/wp-content/uploads/2023/12/Untitled-design-bj.jpg",
    },
  ];

  export const DealOfTheWeekData = [
    { image: "https://hdwallpaperim.com/wp-content/uploads/2017/08/25/123982-night-urban.jpg", name: "The Wasted Times", season: "Season 1" },
    { image: "https://wallpaper.forfun.com/fetch/19/19b7a7201a24d6d3934b5da031c38307.jpeg", name: "Card 1", season: "Season 1" },
    { image: "https://cdn.pixabay.com/photo/2024/01/02/14/58/leaf-8483401_640.jpg", name: "Card 2", season: "Season 2" },
    { image: "https://images.unsplash.com/photo-1475070929565-c985b496cb9f?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MXx8fGVufDB8fHx8fA%3D%3D", name: "Card 3", season: "Season 3" },
    { image: "https://e0.pxfuel.com/wallpapers/240/1/desktop-wallpaper-cinematic-cool-cinematic.jpg", name: "Card 4", season: "Season 4" },
    { image: "https://e0.pxfuel.com/wallpapers/149/40/desktop-wallpaper-preview-cliffs-destruction-city-landscape-waterfall.jpg", name: "Card 5", season: "Season 5" },
    { image: "https://wallpapercave.com/wp/wp3704357.jpg", name: "Card 6", season: "Season 6" }

  ]

  export const TopWebSeriesList = [
    { image: "https://wallpaper.forfun.com/fetch/19/19b7a7201a24d6d3934b5da031c38307.jpeg", name: "Card 1", season: "Season 1" },
    { image: "https://cdn.pixabay.com/photo/2024/01/02/14/58/leaf-8483401_640.jpg", name: "Card 2", season: "Season 2" },
    { image: "https://images.unsplash.com/photo-1475070929565-c985b496cb9f?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MXx8fGVufDB8fHx8fA%3D%3D", name: "Card 3", season: "Season 3" },
    { image: "https://e0.pxfuel.com/wallpapers/240/1/desktop-wallpaper-cinematic-cool-cinematic.jpg", name: "Card 4", season: "Season 4" },
    { image: "https://e0.pxfuel.com/wallpapers/149/40/desktop-wallpaper-preview-cliffs-destruction-city-landscape-waterfall.jpg", name: "Card 5", season: "Season 5" },
    { image: "https://wallpapercave.com/wp/wp3704357.jpg", name: "Card 6", season: "Season 6" }
];

  export const OTTKingSportsList = [
  "https://www.ottking.info/wp-content/uploads/2023/11/SPORTS-1.jpg",
  "https://www.ottking.info/wp-content/uploads/2023/11/sports-2.jpg",
  "https://www.ottking.info/wp-content/uploads/2023/11/Untitled-design-3-8.jpg",
  "https://www.ottking.info/wp-content/uploads/2023/11/Untitled-design4.jpg",
  "https://www.ottking.info/wp-content/uploads/2023/11/Untitled-design4.jpg",
  "https://www.ottking.info/wp-content/uploads/2023/11/Untitled-design-5-7.jpg",
  "https://m.media-amazon.com/images/I/915xJIYLb+L.jpg",
  "https://m.media-amazon.com/images/I/915xJIYLb+L.jpg",
];

  export const OTTKingSpecialsList = [
  "https://m.media-amazon.com/images/I/915xJIYLb+L.jpg",
  "https://m.media-amazon.com/images/M/MV5BNGE0NzE5Y2ItYjQ3Zi00YzNiLWFhNmMtODhkNjFhNzQ5ZGFlXkEyXkFqcGc@._V1_.jpg",
  "https://m.media-amazon.com/images/I/915xJIYLb+L.jpg",
  "https://m.media-amazon.com/images/I/915xJIYLb+L.jpg",
  "https://m.media-amazon.com/images/I/915xJIYLb+L.jpg",
  "https://m.media-amazon.com/images/M/MV5BNGE0NzE5Y2ItYjQ3Zi00YzNiLWFhNmMtODhkNjFhNzQ5ZGFlXkEyXkFqcGc@._V1_.jpg",
  "https://m.media-amazon.com/images/I/915xJIYLb+L.jpg",
  "https://m.media-amazon.com/images/I/915xJIYLb+L.jpg",
];

  export const plansData = [
  {
    name: "Basic Plan",
    price: "Free",
    features: [
      "✓ Get unlimited access to thousands of shows and movies with limited ads", 
      "✓ Watch on your favorite devices", 
      "✓ Switch plans or cancel anytime", 
      "✓ Download from thousands of titles to watch offline"
    ],
  },
  {
    name: "Gold Plan",
    price: "$19.99/month",
    features: [
      "✓ Get unlimited access to thousands of shows and movies with limited ads", 
      "✓ Watch on your favorite devices", 
      "✓ Switch plans or cancel anytime", 
      "✓ Download from thousands of titles to watch offline"
    ],
  },
  {
    name: "Diamond Plan",
    price: "$29.99/month",
    features: [
      "✓ Get unlimited access to thousands of shows and movies with limited ads", 
      "✓ Watch on your favorite devices", 
      "✓ Switch plans or cancel anytime", 
      "✓ Download from thousands of titles to watch offline"
    ],
  },
];

  export const logoList = [
  [
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
    'https://upload.wikimedia.org/wikipedia/commons/5/5a/Zee5-official-logo.jpeg',
    'https://play-lh.googleusercontent.com/-qJGSkZMRoaFIk4dwqwWQ_mRIFs5XbeX2GIXv8S4vq8YzaHJ5boOEwjayyZY8G0u2jE',
    'https://play-lh.googleusercontent.com/27MJyZrte7jaPCkmXETN6-6Bry93Tmb4Jmz3rREJrDrjQ0HNcXrlD90KrNkf6L_bpDw',
    'https://play-lh.googleusercontent.com/bIYlrMjal6an_GSBsn-k6NevSC5yv7q_0ej8ZVM_1Br_UEeG0-chDO2xS5JI4Xw3sQ',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
    'https://play-lh.googleusercontent.com/bIYlrMjal6an_GSBsn-k6NevSC5yv7q_0ej8ZVM_1Br_UEeG0-chDO2xS5JI4Xw3sQ',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
  ], 
  [
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
    'https://upload.wikimedia.org/wikipedia/commons/5/5a/Zee5-official-logo.jpeg',
    'https://play-lh.googleusercontent.com/-qJGSkZMRoaFIk4dwqwWQ_mRIFs5XbeX2GIXv8S4vq8YzaHJ5boOEwjayyZY8G0u2jE',
    'https://play-lh.googleusercontent.com/27MJyZrte7jaPCkmXETN6-6Bry93Tmb4Jmz3rREJrDrjQ0HNcXrlD90KrNkf6L_bpDw',
    'https://play-lh.googleusercontent.com/bIYlrMjal6an_GSBsn-k6NevSC5yv7q_0ej8ZVM_1Br_UEeG0-chDO2xS5JI4Xw3sQ',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
    'https://play-lh.googleusercontent.com/bIYlrMjal6an_GSBsn-k6NevSC5yv7q_0ej8ZVM_1Br_UEeG0-chDO2xS5JI4Xw3sQ',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
    'https://play-lh.googleusercontent.com/bIYlrMjal6an_GSBsn-k6NevSC5yv7q_0ej8ZVM_1Br_UEeG0-chDO2xS5JI4Xw3sQ',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
    'https://play-lh.googleusercontent.com/bIYlrMjal6an_GSBsn-k6NevSC5yv7q_0ej8ZVM_1Br_UEeG0-chDO2xS5JI4Xw3sQ',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
    'https://play-lh.googleusercontent.com/-qJGSkZMRoaFIk4dwqwWQ_mRIFs5XbeX2GIXv8S4vq8YzaHJ5boOEwjayyZY8G0u2jE',
    'https://play-lh.googleusercontent.com/27MJyZrte7jaPCkmXETN6-6Bry93Tmb4Jmz3rREJrDrjQ0HNcXrlD90KrNkf6L_bpDw',
    'https://play-lh.googleusercontent.com/bIYlrMjal6an_GSBsn-k6NevSC5yv7q_0ej8ZVM_1Br_UEeG0-chDO2xS5JI4Xw3sQ',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s'
  ],
  [
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
    'https://upload.wikimedia.org/wikipedia/commons/5/5a/Zee5-official-logo.jpeg',
    'https://play-lh.googleusercontent.com/-qJGSkZMRoaFIk4dwqwWQ_mRIFs5XbeX2GIXv8S4vq8YzaHJ5boOEwjayyZY8G0u2jE',
    'https://play-lh.googleusercontent.com/27MJyZrte7jaPCkmXETN6-6Bry93Tmb4Jmz3rREJrDrjQ0HNcXrlD90KrNkf6L_bpDw',
    'https://play-lh.googleusercontent.com/bIYlrMjal6an_GSBsn-k6NevSC5yv7q_0ej8ZVM_1Br_UEeG0-chDO2xS5JI4Xw3sQ',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
    'https://play-lh.googleusercontent.com/bIYlrMjal6an_GSBsn-k6NevSC5yv7q_0ej8ZVM_1Br_UEeG0-chDO2xS5JI4Xw3sQ',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
    'https://play-lh.googleusercontent.com/bIYlrMjal6an_GSBsn-k6NevSC5yv7q_0ej8ZVM_1Br_UEeG0-chDO2xS5JI4Xw3sQ',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
    'https://play-lh.googleusercontent.com/bIYlrMjal6an_GSBsn-k6NevSC5yv7q_0ej8ZVM_1Br_UEeG0-chDO2xS5JI4Xw3sQ',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
    'https://play-lh.googleusercontent.com/bIYlrMjal6an_GSBsn-k6NevSC5yv7q_0ej8ZVM_1Br_UEeG0-chDO2xS5JI4Xw3sQ',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
    'https://play-lh.googleusercontent.com/bIYlrMjal6an_GSBsn-k6NevSC5yv7q_0ej8ZVM_1Br_UEeG0-chDO2xS5JI4Xw3sQ',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
    'https://upload.wikimedia.org/wikipedia/commons/5/5a/Zee5-official-logo.jpeg',
    'https://play-lh.googleusercontent.com/-qJGSkZMRoaFIk4dwqwWQ_mRIFs5XbeX2GIXv8S4vq8YzaHJ5boOEwjayyZY8G0u2jE',
    'https://play-lh.googleusercontent.com/27MJyZrte7jaPCkmXETN6-6Bry93Tmb4Jmz3rREJrDrjQ0HNcXrlD90KrNkf6L_bpDw',
    'https://play-lh.googleusercontent.com/bIYlrMjal6an_GSBsn-k6NevSC5yv7q_0ej8ZVM_1Br_UEeG0-chDO2xS5JI4Xw3sQ',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
    'https://play-lh.googleusercontent.com/bIYlrMjal6an_GSBsn-k6NevSC5yv7q_0ej8ZVM_1Br_UEeG0-chDO2xS5JI4Xw3sQ',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
    'https://play-lh.googleusercontent.com/bIYlrMjal6an_GSBsn-k6NevSC5yv7q_0ej8ZVM_1Br_UEeG0-chDO2xS5JI4Xw3sQ',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
    'https://play-lh.googleusercontent.com/bIYlrMjal6an_GSBsn-k6NevSC5yv7q_0ej8ZVM_1Br_UEeG0-chDO2xS5JI4Xw3sQ',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
    'https://play-lh.googleusercontent.com/bIYlrMjal6an_GSBsn-k6NevSC5yv7q_0ej8ZVM_1Br_UEeG0-chDO2xS5JI4Xw3sQ',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s',
    'https://play-lh.googleusercontent.com/bIYlrMjal6an_GSBsn-k6NevSC5yv7q_0ej8ZVM_1Br_UEeG0-chDO2xS5JI4Xw3sQ',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgcwWkYHYoyEQgeLZNszkwQo135F_JfVR6w&s'
  ]
]